apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/part-of: hatch
    app.kubernetes.io/component: postgres
spec:
  selector:
    app.kubernetes.io/component: postgres
  ports:
    - port: {{ .Values.postgres.servicePort }}
      targetPort: postgres
      name: postgres
