-- API keys are 32 random bytes generated by the API, so a plain SHA-256 is
-- enough to store them: a slow password hash only helps against guessable
-- secrets. api_key_lookup is both the index a request's client is found by and
-- the credential check itself.
CREATE TABLE clients (
    id              bytea       PRIMARY KEY,
    name            text        NOT NULL,
    api_key_lookup  bytea       NOT NULL UNIQUE,
    is_active       boolean     NOT NULL DEFAULT true,
    max_rps         integer     NOT NULL DEFAULT 100,
    created_at      timestamptz NOT NULL DEFAULT now()
);
