// benchreport aggregates the per-point JSON files a benchmark suite produced
// into the committed reference set: one machine-readable file and one table.
//
// It exists so no number in the repository is ever transcribed by hand. The
// interpretation lives in docs/BENCHMARKS.md and cites this output; if the two
// ever disagree, this one is the measurement.
//
//	go run ./cmd/benchreport <input-dir> <output-dir>
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/mdhishaamakhtar/hatch/internal/bench"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: benchreport <input-dir> <output-dir>")
		os.Exit(2)
	}
	if err := run(os.Args[1], os.Args[2]); err != nil {
		fmt.Fprintln(os.Stderr, "benchreport:", err)
		os.Exit(1)
	}
}

// reference is the whole committed artifact: the environment the numbers came
// from, then every point.
type reference struct {
	GeneratedAt time.Time       `json:"generated_at"`
	GitCommit   string          `json:"git_commit"`
	Host        string          `json:"host"`
	Results     []*bench.Result `json:"results"`
}

func run(inDir, outDir string) error {
	paths, err := filepath.Glob(filepath.Join(inDir, "*.json"))
	if err != nil {
		return err
	}
	if len(paths) == 0 {
		return fmt.Errorf("no result files in %s", inDir)
	}
	sort.Strings(paths)

	ref := reference{
		GeneratedAt: time.Now().UTC(),
		GitCommit:   shell("git", "rev-parse", "--short", "HEAD"),
		Host:        hostDescription(),
	}
	for _, p := range paths {
		raw, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		var res bench.Result
		if err := json.Unmarshal(raw, &res); err != nil {
			return fmt.Errorf("%s: %w", filepath.Base(p), err)
		}
		ref.Results = append(ref.Results, &res)
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	jsonPath := filepath.Join(outDir, "reference.json")
	raw, err := json.MarshalIndent(ref, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(jsonPath, raw, 0o644); err != nil {
		return err
	}
	mdPath := filepath.Join(outDir, "reference.md")
	if err := os.WriteFile(mdPath, []byte(ref.markdown()), 0o644); err != nil {
		return err
	}

	fmt.Printf("wrote %s (%d points)\n", mdPath, len(ref.Results))
	fmt.Printf("wrote %s\n", jsonPath)
	return nil
}

func (r reference) markdown() string {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p("# Hatch benchmark — reference run")
	p("")
	p("Generated by `make bench-all`. Every number here is written by the harness;")
	p("none is typed by hand. The interpretation lives in")
	p("[docs/BENCHMARKS.md](../docs/BENCHMARKS.md).")
	p("")
	p("| | |")
	p("|---|---|")
	p("| Generated | %s |", r.GeneratedAt.Format(time.RFC3339))
	p("| Commit | `%s` |", r.GitCommit)
	p("| Host | %s |", r.Host)

	p("")
	p("## Ingest — schedules accepted per second")
	p("")
	p("| Run | Clients | Created | Achieved/sec | p50 | p95 | p99 |")
	p("|---|---|---|---|---|---|---|")
	for _, res := range r.Results {
		if res.Scenario != "ingest" || res.Load == nil {
			continue
		}
		l := res.Load
		p("| %s | %d | %d | **%.1f** | %s | %s | %s |",
			res.Label, l.Attempted, l.Created, l.AchievedRPS,
			round(l.Latency.P50), round(l.Latency.P95), round(l.Latency.P99))
	}

	p("")
	p("## Delivery — emails sent per second")
	p("")
	p("| Run | Workers | Delivered | Sustained/sec | Per hour | Window | Final states |")
	p("|---|---|---|---|---|---|---|")
	for _, res := range r.Results {
		if res.Scenario != "delivery" || res.Drain == nil {
			continue
		}
		d := res.Drain
		counts := ""
		if res.Counts != nil {
			counts = res.Counts.String()
		}
		p("| %s | %d | %d | **%.2f** | %s | %s | %s |",
			res.Label, res.Replicas["delivery-worker"], deliveredOf(res),
			d.DeliveredPerSec, perHour(d.DeliveredPerSec), d.WorkerWindow, counts)
	}

	p("")
	p("## Punctuality — how long after deliver_at the email actually went out")
	p("")
	p("| Run | p50 | p95 | p99 | Delivered | In flight at end |")
	p("|---|---|---|---|---|---|")
	for _, res := range r.Results {
		if res.E2E == nil {
			continue
		}
		inFlight := 0
		if res.Counts != nil {
			inFlight = res.Counts.InFlight()
		}
		p("| %s | %s | %s | %s | %d | %d |",
			res.Label, secs(res.E2E.P50), secs(res.E2E.P95), secs(res.E2E.P99),
			deliveredOf(res), inFlight)
	}

	p("")
	p("## Run integrity")
	p("")
	p("Whether each run was *valid* — every schedule reached a terminal state and")
	p("nothing was left in flight. These are not performance targets. A failure here")
	p("means the numbers above cannot be read at face value; it does not mean the")
	p("system was slow.")
	p("")
	p("| Run | Check | Expected | Actual | |")
	p("|---|---|---|---|---|")
	integrity := 0
	for _, res := range r.Results {
		for _, c := range res.Checks {
			mark := "FAIL"
			if c.Pass {
				mark = "ok"
			} else {
				integrity++
			}
			p("| %s | %s | %s | %s | %s |", res.Label, c.Name, c.Expected, c.Actual, mark)
		}
	}
	p("")
	if integrity == 0 {
		p("All checks passed.")
	} else {
		p("**%d check(s) failed** — see the affected points below before citing them.", integrity)
	}

	p("")
	p("## Every point in full")
	for _, res := range r.Results {
		p("")
		p("### %s — %s", res.Scenario, res.Label)
		p("")
		p("```")
		p("%s", strings.TrimSpace(res.Markdown()))
		p("```")
	}
	return b.String()
}

func deliveredOf(res *bench.Result) int {
	if res.Counts == nil {
		return 0
	}
	return res.Counts.Delivered
}

// perHour renders a per-second rate at the scale the question is usually asked
// in: "can this absorb N emails in an hour".
func perHour(perSec float64) string {
	switch n := perSec * 3600; {
	case n >= 1_000_000:
		return fmt.Sprintf("%.1fM", n/1_000_000)
	case n >= 1_000:
		return fmt.Sprintf("%.0fk", n/1_000)
	default:
		return fmt.Sprintf("%.0f", n)
	}
}

func secs(v float64) string {
	return time.Duration(v * float64(time.Second)).Round(time.Millisecond).String()
}

func round(d time.Duration) string { return d.Round(time.Millisecond).String() }

func shell(name string, args ...string) string {
	out, err := exec.Command(name, args...).Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(out))
}

// hostDescription records the machine, because every absolute number here is
// relative to it.
func hostDescription() string {
	cpu := shell("sysctl", "-n", "machdep.cpu.brand_string")
	cores := shell("sysctl", "-n", "hw.ncpu")
	if cpu == "unknown" {
		return "unknown"
	}
	return fmt.Sprintf("%s, %s cores", cpu, cores)
}
