// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/clients": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create a client",
                "parameters": [
                    {
                        "description": "The client",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/createClientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/createClientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    }
                }
            }
        },
        "/admin/clients/{client_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Delete a client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client id",
                        "name": "client_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    }
                }
            }
        },
        "/admin/clients/{client_id}/providers": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Register a client's provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client id",
                        "name": "client_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Vendor and credentials, such as an api_key for resend",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/upsertProviderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/upsertProviderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    }
                }
            }
        },
        "/admin/clients/{client_id}/providers/{vendor}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Delete a client's provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client id",
                        "name": "client_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "mock",
                            "resend"
                        ],
                        "type": "string",
                        "description": "Vendor",
                        "name": "vendor",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    }
                }
            }
        },
        "/v1/schedules": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Schedule an email",
                "parameters": [
                    {
                        "description": "The email and when to send it",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/createScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Idempotent replay",
                        "schema": {
                            "$ref": "#/definitions/scheduleResponse"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/scheduleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    }
                }
            }
        },
        "/v1/schedules/{schedule_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Get a schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Schedule id",
                        "name": "schedule_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scheduleDetail"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Cancel a schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Schedule id",
                        "name": "schedule_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Already delivered, failed or cancelled",
                        "schema": {
                            "$ref": "#/definitions/ErrorBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ErrorBody": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "createClientRequest": {
            "type": "object",
            "properties": {
                "max_rps": {
                    "description": "defaults to 100",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "createClientResponse": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "client_id": {
                    "type": "string"
                },
                "max_rps": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "createScheduleRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "deliver_at": {
                    "description": "Unix milliseconds",
                    "type": "integer"
                },
                "from_email": {
                    "type": "string"
                },
                "from_name": {
                    "type": "string"
                },
                "idempotency_key": {
                    "type": "string"
                },
                "metadata": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "recipient_email": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "scheduleDetail": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deliver_at": {
                    "type": "integer"
                },
                "failure_reason": {
                    "type": "string"
                },
                "from_email": {
                    "type": "string"
                },
                "from_name": {
                    "type": "string"
                },
                "idempotency_key": {
                    "type": "string"
                },
                "last_provider": {
                    "type": "string"
                },
                "metadata": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "recipient_email": {
                    "type": "string"
                },
                "retry_count": {
                    "type": "integer"
                },
                "schedule_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "scheduleResponse": {
            "type": "object",
            "properties": {
                "deliver_at": {
                    "type": "integer"
                },
                "schedule_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "upsertProviderRequest": {
            "type": "object",
            "properties": {
                "credentials": {
                    "type": "object"
                },
                "vendor": {
                    "type": "string",
                    "enum": [
                        "mock",
                        "resend"
                    ]
                }
            }
        },
        "upsertProviderResponse": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "provider_id": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "\"Bearer \u003capi_key\u003e\": a client's key for /v1, the admin key for /admin.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9021",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Hatch Scheduler API",
	Description:      "Schedule emails for future delivery. Admin endpoints provision clients and their providers' credentials.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
