// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api.sql

package db

import (
	"context"
	"time"
)

const cancelSchedule = `-- name: CancelSchedule :execrows
UPDATE scheduled_emails
SET status = 'cancelled',
    updated_at = now()
WHERE id = $1
  AND deliver_at = $2
  AND client_id = $3
  AND status IN ('pending', 'processing', 'retrying')
`

type CancelScheduleParams struct {
	ID        []byte
	DeliverAt time.Time
	ClientID  []byte
}

func (q *Queries) CancelSchedule(ctx context.Context, arg CancelScheduleParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelSchedule, arg.ID, arg.DeliverAt, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createClient = `-- name: CreateClient :exec
INSERT INTO clients (id, name, api_key_lookup, max_rps)
VALUES ($1, $2, $3, $4)
`

type CreateClientParams struct {
	ID           []byte
	Name         string
	ApiKeyLookup []byte
	MaxRps       int32
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) error {
	_, err := q.db.Exec(ctx, createClient,
		arg.ID,
		arg.Name,
		arg.ApiKeyLookup,
		arg.MaxRps,
	)
	return err
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO scheduled_emails (
    id, client_id, deliver_at, recipient_email, from_email, from_name, subject, body, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING status
`

type CreateScheduleParams struct {
	ID             []byte
	ClientID       []byte
	DeliverAt      time.Time
	RecipientEmail string
	FromEmail      string
	FromName       *string
	Subject        string
	Body           string
	Metadata       []byte
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (ScheduleStatus, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.ID,
		arg.ClientID,
		arg.DeliverAt,
		arg.RecipientEmail,
		arg.FromEmail,
		arg.FromName,
		arg.Subject,
		arg.Body,
		arg.Metadata,
	)
	var status ScheduleStatus
	err := row.Scan(&status)
	return status, err
}

const createScheduleWithKey = `-- name: CreateScheduleWithKey :one
WITH claimed AS (
    INSERT INTO schedule_idempotency (client_id, idempotency_key, schedule_id)
    VALUES ($1, $2, $10)
    ON CONFLICT DO NOTHING
    RETURNING schedule_id
)
INSERT INTO scheduled_emails (
    id, client_id, idempotency_key, deliver_at, recipient_email, from_email, from_name, subject, body, metadata
)
SELECT schedule_id,
       $1::bytea,
       $2::text,
       $3::timestamptz,
       $4::text,
       $5::text,
       $6::text,
       $7::text,
       $8::text,
       $9::jsonb
FROM claimed
RETURNING status
`

type CreateScheduleWithKeyParams struct {
	ClientID       []byte
	IdempotencyKey string
	DeliverAt      time.Time
	RecipientEmail string
	FromEmail      string
	FromName       *string
	Subject        string
	Body           string
	Metadata       []byte
	ID             []byte
}

// Claims the idempotency key and inserts the schedule in one statement, so the
// two can never disagree. When the key is already taken nothing is inserted and
// no row comes back.
func (q *Queries) CreateScheduleWithKey(ctx context.Context, arg CreateScheduleWithKeyParams) (ScheduleStatus, error) {
	row := q.db.QueryRow(ctx, createScheduleWithKey,
		arg.ClientID,
		arg.IdempotencyKey,
		arg.DeliverAt,
		arg.RecipientEmail,
		arg.FromEmail,
		arg.FromName,
		arg.Subject,
		arg.Body,
		arg.Metadata,
		arg.ID,
	)
	var status ScheduleStatus
	err := row.Scan(&status)
	return status, err
}

const deactivateClient = `-- name: DeactivateClient :exec
UPDATE clients
SET is_active = false
WHERE id = $1
`

func (q *Queries) DeactivateClient(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, deactivateClient, id)
	return err
}

const deactivateClientProvider = `-- name: DeactivateClientProvider :exec
UPDATE client_providers
SET is_active = false
WHERE client_id = $1
  AND vendor = $2
`

type DeactivateClientProviderParams struct {
	ClientID []byte
	Vendor   string
}

func (q *Queries) DeactivateClientProvider(ctx context.Context, arg DeactivateClientProviderParams) error {
	_, err := q.db.Exec(ctx, deactivateClientProvider, arg.ClientID, arg.Vendor)
	return err
}

const getClientByAPIKey = `-- name: GetClientByAPIKey :one
SELECT id, max_rps,
       EXISTS (SELECT 1 FROM client_providers p WHERE p.client_id = clients.id AND p.is_active) AS has_provider
FROM clients
WHERE api_key_lookup = $1
  AND is_active
`

type GetClientByAPIKeyRow struct {
	ID          []byte
	MaxRps      int32
	HasProvider bool
}

// Authenticates a request. Whether the client can send at all rides along, so
// creating a schedule needs no extra round trip to check it.
func (q *Queries) GetClientByAPIKey(ctx context.Context, apiKeyLookup []byte) (GetClientByAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getClientByAPIKey, apiKeyLookup)
	var i GetClientByAPIKeyRow
	err := row.Scan(&i.ID, &i.MaxRps, &i.HasProvider)
	return i, err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, client_id, idempotency_key, deliver_at, status, recipient_email, from_email, from_name, subject, body, metadata, retry_count, last_provider, failure_reason, created_at, updated_at
FROM scheduled_emails
WHERE id = $1
  AND deliver_at = $2
  AND client_id = $3
`

type GetScheduleParams struct {
	ID        []byte
	DeliverAt time.Time
	ClientID  []byte
}

func (q *Queries) GetSchedule(ctx context.Context, arg GetScheduleParams) (ScheduledEmail, error) {
	row := q.db.QueryRow(ctx, getSchedule, arg.ID, arg.DeliverAt, arg.ClientID)
	var i ScheduledEmail
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.IdempotencyKey,
		&i.DeliverAt,
		&i.Status,
		&i.RecipientEmail,
		&i.FromEmail,
		&i.FromName,
		&i.Subject,
		&i.Body,
		&i.Metadata,
		&i.RetryCount,
		&i.LastProvider,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduleIDByKey = `-- name: GetScheduleIDByKey :one
SELECT schedule_id
FROM schedule_idempotency
WHERE client_id = $1
  AND idempotency_key = $2
`

type GetScheduleIDByKeyParams struct {
	ClientID       []byte
	IdempotencyKey string
}

func (q *Queries) GetScheduleIDByKey(ctx context.Context, arg GetScheduleIDByKeyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getScheduleIDByKey, arg.ClientID, arg.IdempotencyKey)
	var schedule_id []byte
	err := row.Scan(&schedule_id)
	return schedule_id, err
}

const upsertClientProvider = `-- name: UpsertClientProvider :one
INSERT INTO client_providers (id, client_id, vendor, credentials)
VALUES ($1, $2, $3, $4)
ON CONFLICT (client_id, vendor) DO UPDATE
SET credentials = EXCLUDED.credentials,
    is_active = true
RETURNING id
`

type UpsertClientProviderParams struct {
	ID          []byte
	ClientID    []byte
	Vendor      string
	Credentials []byte
}

func (q *Queries) UpsertClientProvider(ctx context.Context, arg UpsertClientProviderParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, upsertClientProvider,
		arg.ID,
		arg.ClientID,
		arg.Vendor,
		arg.Credentials,
	)
	var id []byte
	err := row.Scan(&id)
	return id, err
}
