// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package db

import (
	"context"
	"time"
)

const getSchedules = `-- name: GetSchedules :many
SELECT id, client_id, idempotency_key, deliver_at, status, recipient_email, from_email, from_name, subject, body, metadata, retry_count, last_provider, failure_reason, created_at, updated_at
FROM scheduled_emails
WHERE id = ANY($1::bytea[])
  AND deliver_at = ANY($2::timestamptz[])
`

type GetSchedulesParams struct {
	Ids        [][]byte
	DeliverAts []time.Time
}

// deliver_ats must hold the deliver_at of every id: it is what lets Postgres
// prune to the partitions involved instead of probing all of them.
func (q *Queries) GetSchedules(ctx context.Context, arg GetSchedulesParams) ([]ScheduledEmail, error) {
	rows, err := q.db.Query(ctx, getSchedules, arg.Ids, arg.DeliverAts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledEmail
	for rows.Next() {
		var i ScheduledEmail
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.IdempotencyKey,
			&i.DeliverAt,
			&i.Status,
			&i.RecipientEmail,
			&i.FromEmail,
			&i.FromName,
			&i.Subject,
			&i.Body,
			&i.Metadata,
			&i.RetryCount,
			&i.LastProvider,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isClientActive = `-- name: IsClientActive :one
SELECT is_active
FROM clients
WHERE id = $1
`

func (q *Queries) IsClientActive(ctx context.Context, id []byte) (bool, error) {
	row := q.db.QueryRow(ctx, isClientActive, id)
	var is_active bool
	err := row.Scan(&is_active)
	return is_active, err
}

const listActiveProviders = `-- name: ListActiveProviders :many
SELECT vendor, credentials
FROM client_providers
WHERE client_id = $1
  AND is_active
`

type ListActiveProvidersRow struct {
	Vendor      string
	Credentials []byte
}

func (q *Queries) ListActiveProviders(ctx context.Context, clientID []byte) ([]ListActiveProvidersRow, error) {
	rows, err := q.db.Query(ctx, listActiveProviders, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveProvidersRow
	for rows.Next() {
		var i ListActiveProvidersRow
		if err := rows.Scan(&i.Vendor, &i.Credentials); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCancelled = `-- name: MarkCancelled :execrows
UPDATE scheduled_emails
SET status = 'cancelled',
    failure_reason = $3,
    updated_at = now()
WHERE id = $1
  AND deliver_at = $2
  AND status = 'processing'
`

type MarkCancelledParams struct {
	ID            []byte
	DeliverAt     time.Time
	FailureReason *string
}

func (q *Queries) MarkCancelled(ctx context.Context, arg MarkCancelledParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCancelled, arg.ID, arg.DeliverAt, arg.FailureReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDelivered = `-- name: MarkDelivered :execrows
UPDATE scheduled_emails
SET status = 'delivered',
    last_provider = $3,
    updated_at = now()
WHERE id = $1
  AND deliver_at = $2
  AND status = 'processing'
`

type MarkDeliveredParams struct {
	ID           []byte
	DeliverAt    time.Time
	LastProvider *string
}

func (q *Queries) MarkDelivered(ctx context.Context, arg MarkDeliveredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDelivered, arg.ID, arg.DeliverAt, arg.LastProvider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markFailed = `-- name: MarkFailed :execrows
UPDATE scheduled_emails
SET status = 'failed',
    last_provider = $3,
    failure_reason = $4,
    updated_at = now()
WHERE id = $1
  AND deliver_at = $2
  AND status = 'processing'
`

type MarkFailedParams struct {
	ID            []byte
	DeliverAt     time.Time
	LastProvider  *string
	FailureReason *string
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markFailed,
		arg.ID,
		arg.DeliverAt,
		arg.LastProvider,
		arg.FailureReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markProcessing = `-- name: MarkProcessing :execrows

UPDATE scheduled_emails
SET status = 'processing',
    updated_at = now()
WHERE id = $1
  AND deliver_at = $2
  AND status IN ('pending', 'processing', 'retrying')
`

type MarkProcessingParams struct {
	ID        []byte
	DeliverAt time.Time
}

// Every Mark* guards its transition with a status predicate and reports the rows
// it changed, so terminal states are sticky: a duplicate emails.due record, or a
// cancel that lands mid-send, changes nothing instead of rewriting the outcome.
func (q *Queries) MarkProcessing(ctx context.Context, arg MarkProcessingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markProcessing, arg.ID, arg.DeliverAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRetrying = `-- name: MarkRetrying :execrows
UPDATE scheduled_emails
SET status = 'retrying',
    retry_count = retry_count + 1,
    last_provider = $3,
    failure_reason = $4,
    updated_at = now()
WHERE id = $1
  AND deliver_at = $2
  AND status = 'processing'
`

type MarkRetryingParams struct {
	ID            []byte
	DeliverAt     time.Time
	LastProvider  *string
	FailureReason *string
}

func (q *Queries) MarkRetrying(ctx context.Context, arg MarkRetryingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRetrying,
		arg.ID,
		arg.DeliverAt,
		arg.LastProvider,
		arg.FailureReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
