// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type ScheduleStatus string

const (
	ScheduleStatusPending    ScheduleStatus = "pending"
	ScheduleStatusProcessing ScheduleStatus = "processing"
	ScheduleStatusRetrying   ScheduleStatus = "retrying"
	ScheduleStatusDelivered  ScheduleStatus = "delivered"
	ScheduleStatusFailed     ScheduleStatus = "failed"
	ScheduleStatusCancelled  ScheduleStatus = "cancelled"
)

func (e *ScheduleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScheduleStatus(s)
	case string:
		*e = ScheduleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ScheduleStatus: %T", src)
	}
	return nil
}

type NullScheduleStatus struct {
	ScheduleStatus ScheduleStatus
	Valid          bool // Valid is true if ScheduleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScheduleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ScheduleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScheduleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScheduleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScheduleStatus), nil
}

type Client struct {
	ID           []byte
	Name         string
	ApiKeyLookup []byte
	IsActive     bool
	MaxRps       int32
	CreatedAt    time.Time
}

type ClientProvider struct {
	ID          []byte
	ClientID    []byte
	Vendor      string
	Credentials []byte
	IsActive    bool
	CreatedAt   time.Time
}

type ScheduleIdempotency struct {
	ClientID       []byte
	IdempotencyKey string
	ScheduleID     []byte
	CreatedAt      time.Time
}

type ScheduledEmail struct {
	ID             []byte
	ClientID       []byte
	IdempotencyKey *string
	DeliverAt      time.Time
	Status         ScheduleStatus
	RecipientEmail string
	FromEmail      string
	FromName       *string
	Subject        string
	Body           string
	Metadata       []byte
	RetryCount     int16
	LastProvider   *string
	FailureReason  *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
