// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recon.sql

package db

import (
	"context"
)

const recoverOrphanedRetries = `-- name: RecoverOrphanedRetries :many
UPDATE scheduled_emails
SET status = 'processing',
    updated_at = now()
WHERE status = 'retrying'
  AND updated_at < now() - interval '2 hours'
RETURNING id
`

// Rows left retrying whose re-enqueue never happened. The failed attempt did
// count, so retry_count and last_provider are kept.
func (q *Queries) RecoverOrphanedRetries(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, recoverOrphanedRetries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var id []byte
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverUnattempted = `-- name: RecoverUnattempted :many
UPDATE scheduled_emails
SET status = 'processing',
    retry_count = 0,
    last_provider = NULL,
    updated_at = now()
WHERE (status = 'pending' AND deliver_at < now() - interval '5 minutes')
   OR (status = 'processing' AND updated_at < now() - interval '10 minutes')
RETURNING id
`

// Rows no delivery attempt ever finished: pending past their deliver_at (the
// scheduler never fired them), or processing for too long (the worker died
// mid-send). Retry state is reset because no attempt counted.
//
// The grace on pending rows matters: a row fired seconds ago stays pending
// until a worker picks it up, and claiming those would only create duplicates.
func (q *Queries) RecoverUnattempted(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, recoverUnattempted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var id []byte
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
