// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package db

import (
	"context"
	"time"
)

const listDue = `-- name: ListDue :many
SELECT id, deliver_at
FROM scheduled_emails
WHERE status = 'pending'
  AND deliver_at > $1
  AND deliver_at <= $2
  AND (hashtextextended(encode(id, 'hex'), 0) & 2147483647) % $3::int = $4::int
`

type ListDueParams struct {
	After     time.Time
	Until     time.Time
	TotalPods int32
	PodIndex  int32
}

type ListDueRow struct {
	ID        []byte
	DeliverAt time.Time
}

// The pending schedules in this pod's shard that fall due in (after, until].
func (q *Queries) ListDue(ctx context.Context, arg ListDueParams) ([]ListDueRow, error) {
	rows, err := q.db.Query(ctx, listDue,
		arg.After,
		arg.Until,
		arg.TotalPods,
		arg.PodIndex,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueRow
	for rows.Next() {
		var i ListDueRow
		if err := rows.Scan(&i.ID, &i.DeliverAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
